version: "3.3"

services:
    ui:
        build:
            context: ./services/ui
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - './services/ui:/usr/src/app'

    users:
        build:
            context: ./services/users
            dockerfile: Dockerfile
        ports:
            - "5001:5000"
        volumes:
            - './services/users:/usr/src/app'

    users-db:
        build:
            context: ./services/users/db
            dockerfile: Dockerfile
        ports:
            - "5435:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    movies:
        build:
            context: ./services/movies
            dockerfile: Dockerfile
        ports:
            - "5002:5000"
        volumes:
            - './services/movies:/usr/src/app'

    movies-db:
        build:
            context: ./services/movies/db
            dockerfile: Dockerfile
        ports:
            - "5436:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
